### ISSUE TITLE
Should be able to re-use Existing VirtualEnv

### ISSUE THREAD

**Issue by greggigon** [cloudify-cosmo/cloudify-agent-packager#5]
It would be great to be able to use existing Env. 
Rather than failing or forcing removal of Virtualenv it would be great if packager would carry on with the existing one.
We are actually using a real Python 2.7.6 statically compiled for agent, so that we don't have any Python dependency on our RHEL boxes.

**Comment by nir0s** [comment]
By existing you mean activated, right?

also, can you share how you're compiling your static Python?

**Comment by nir0s** [comment]
Handled this. Now supported in version 3.5.1

**Comment by greggigon** [comment]
Great stuff, thanks Nir
